version: 0.2

env:
 variables:
    DATABASE_URL: ${DATABASE_URL}
    JWT_SECRET: ${JWT_SECRET}
    
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install --legacy-peer-deps
  build:
    commands:
      - npx prisma generate
      - npx prisma migrate deploy
      - npm run build
artifacts:
  files:
    - '**/*'
